databases:
  - name: postgres
    ipAllowList: []
    databaseName: gym_management_software
    user: gym_management_software

services:
  - type: web
    plan: free
    name: gym_management_software
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false